# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0003_auto_20171119_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phno',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(default=uuid.uuid4, editable=False),
        ),
    ]
