# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0004_auto_20171119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phno',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
