# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0008_auto_20171119_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='otp',
        ),
    ]
